# Generated by Django 4.2 on 2025-04-19 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatOptionNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_description', models.CharField(max_length=250)),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.chat')),
            ],
        ),
        migrations.AlterField(
            model_name='message',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MainApp.chatoptionnode'),
        ),
    ]
