# Generated by Django 4.2 on 2025-04-19 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_chatoptionnode_alter_message_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='root_node',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entry_for', to='MainApp.chatoptionnode'),
        ),
        migrations.AddField(
            model_name='chatoptionnode',
            name='parent_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MainApp.chatoptionnode'),
        ),
        migrations.AlterField(
            model_name='chatoptionnode',
            name='option_description',
            field=models.CharField(blank=True, default='', max_length=250),
        ),
    ]
