# Generated by Django 4.2 on 2025-04-20 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_chat_root_node_chatoptionnode_parent_node_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatoptionnode',
            name='parent_node',
        ),
        migrations.CreateModel(
            name='ChatNodeLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_links', to='MainApp.chatoptionnode')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_links', to='MainApp.chatoptionnode')),
            ],
        ),
    ]
