# Generated by Django 4.2 on 2025-04-20 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_chatoptionnode_pos_x_chatoptionnode_pos_y_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatoptionnode',
            old_name='option_description',
            new_name='description',
        ),
    ]
