# Generated by Django 4.2 on 2025-04-25 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0007_character_avatar_character_display_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='attached_image',
            field=models.ImageField(blank=True, null=True, upload_to='chat_images/'),
        ),
    ]
