# Generated by Django 4.2 on 2025-06-16 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0008_message_attached_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='chat',
            new_name='node',
        ),
    ]
