# Generated by Django 4.2 on 2025-06-17 11:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0009_rename_chat_message_node'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 10, 0, 0, tzinfo=datetime.timezone.utc)),
        ),
    ]
