# Generated by Django 4.2 on 2025-06-21 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0010_alter_message_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatoptionnode',
            name='user_choise',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
